// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_messages.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertInboxMessage = `-- name: InsertInboxMessage :exec
INSERT INTO inbox_messages (message_id, payload_hash, transaction_id)
VALUES ($1, $2, $3)
`

type InsertInboxMessageParams struct {
	MessageID     string
	PayloadHash   string
	TransactionID uuid.UUID
}

func (q *Queries) InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertInboxMessage, arg.MessageID, arg.PayloadHash, arg.TransactionID)
	return err
}

const selectInboxMessage = `-- name: SelectInboxMessage :one
SELECT message_id, payload_hash, transaction_id
FROM inbox_messages
WHERE message_id = $1
`

type SelectInboxMessageRow struct {
	MessageID     string
	PayloadHash   string
	TransactionID uuid.UUID
}

func (q *Queries) SelectInboxMessage(ctx context.Context, messageID string) (SelectInboxMessageRow, error) {
	row := q.db.QueryRow(ctx, selectInboxMessage, messageID)
	var i SelectInboxMessageRow
	err := row.Scan(&i.MessageID, &i.PayloadHash, &i.TransactionID)
	return i, err
}
