// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type OutboxEvent struct {
	ID            uuid.UUID
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	OccurredAt    time.Time
	Attempts      int32
	NextAttemptAt time.Time
	PublishedAt   *time.Time
	CreatedAt     time.Time
	Sequence      int64
}

type WagerTransaction struct {
	ID                             uuid.UUID
	Kind                           string
	State                          string
	WalletID                       uuid.UUID
	PlayerID                       uuid.UUID
	Currency                       string
	AmountMinor                    int64
	ProviderID                     *string
	ExternalTransactionID          *string
	IdempotencyKey                 *string
	PayloadHash                    *string
	RoundID                        *string
	GameID                         *string
	ReferenceExternalTransactionID *string
	ReferenceTransactionID         *uuid.UUID
	FailureCode                    *string
	ResultBalanceMinor             *int64
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
	ReferenceAttempts              int32
	NextAttemptAt                  *time.Time
}

type Wallet struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type WalletLedgerEntry struct {
	ID                 uuid.UUID
	WalletID           uuid.UUID
	TransactionID      uuid.UUID
	Direction          string
	Currency           string
	AmountMinor        int64
	BalanceBeforeMinor int64
	BalanceAfterMinor  int64
	CreatedAt          time.Time
}
