// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_events.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_id, event_type, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxEventParams struct {
	ID          uuid.UUID
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
	OccurredAt  time.Time
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
