// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wager_transactions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertWagerTransaction = `-- name: InsertWagerTransaction :exec
INSERT INTO wager_transactions (
    id,
    kind,
    state,
    wallet_id,
    player_id,
    currency,
    amount_minor,
    provider_id,
    external_transaction_id,
    idempotency_key,
    payload_hash,
    round_id,
    game_id,
    reference_external_transaction_id,
    reference_transaction_id,
    failure_code,
    result_balance_minor
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
`

type InsertWagerTransactionParams struct {
	ID                             uuid.UUID
	Kind                           string
	State                          string
	WalletID                       uuid.UUID
	PlayerID                       uuid.UUID
	Currency                       string
	AmountMinor                    int64
	ProviderID                     *string
	ExternalTransactionID          *string
	IdempotencyKey                 *string
	PayloadHash                    *string
	RoundID                        *string
	GameID                         *string
	ReferenceExternalTransactionID *string
	ReferenceTransactionID         *uuid.UUID
	FailureCode                    *string
	ResultBalanceMinor             *int64
}

func (q *Queries) InsertWagerTransaction(ctx context.Context, arg InsertWagerTransactionParams) error {
	_, err := q.db.Exec(ctx, insertWagerTransaction,
		arg.ID,
		arg.Kind,
		arg.State,
		arg.WalletID,
		arg.PlayerID,
		arg.Currency,
		arg.AmountMinor,
		arg.ProviderID,
		arg.ExternalTransactionID,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.RoundID,
		arg.GameID,
		arg.ReferenceExternalTransactionID,
		arg.ReferenceTransactionID,
		arg.FailureCode,
		arg.ResultBalanceMinor,
	)
	return err
}

const selectWagerTransactionByExternalID = `-- name: SelectWagerTransactionByExternalID :one
SELECT id, kind, state, wallet_id, player_id, currency, amount_minor, provider_id, external_transaction_id, idempotency_key, payload_hash, round_id, game_id, reference_external_transaction_id, reference_transaction_id, failure_code, result_balance_minor, created_at, updated_at
FROM wager_transactions
WHERE provider_id = $1
  AND external_transaction_id = $2
`

type SelectWagerTransactionByExternalIDParams struct {
	ProviderID            *string
	ExternalTransactionID *string
}

func (q *Queries) SelectWagerTransactionByExternalID(ctx context.Context, arg SelectWagerTransactionByExternalIDParams) (WagerTransaction, error) {
	row := q.db.QueryRow(ctx, selectWagerTransactionByExternalID, arg.ProviderID, arg.ExternalTransactionID)
	var i WagerTransaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.WalletID,
		&i.PlayerID,
		&i.Currency,
		&i.AmountMinor,
		&i.ProviderID,
		&i.ExternalTransactionID,
		&i.IdempotencyKey,
		&i.PayloadHash,
		&i.RoundID,
		&i.GameID,
		&i.ReferenceExternalTransactionID,
		&i.ReferenceTransactionID,
		&i.FailureCode,
		&i.ResultBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectWagerTransactionByIdempotencyKey = `-- name: SelectWagerTransactionByIdempotencyKey :one
SELECT id, kind, state, wallet_id, player_id, currency, amount_minor, provider_id, external_transaction_id, idempotency_key, payload_hash, round_id, game_id, reference_external_transaction_id, reference_transaction_id, failure_code, result_balance_minor, created_at, updated_at
FROM wager_transactions
WHERE provider_id = $1
  AND idempotency_key = $2
`

type SelectWagerTransactionByIdempotencyKeyParams struct {
	ProviderID     *string
	IdempotencyKey *string
}

func (q *Queries) SelectWagerTransactionByIdempotencyKey(ctx context.Context, arg SelectWagerTransactionByIdempotencyKeyParams) (WagerTransaction, error) {
	row := q.db.QueryRow(ctx, selectWagerTransactionByIdempotencyKey, arg.ProviderID, arg.IdempotencyKey)
	var i WagerTransaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.WalletID,
		&i.PlayerID,
		&i.Currency,
		&i.AmountMinor,
		&i.ProviderID,
		&i.ExternalTransactionID,
		&i.IdempotencyKey,
		&i.PayloadHash,
		&i.RoundID,
		&i.GameID,
		&i.ReferenceExternalTransactionID,
		&i.ReferenceTransactionID,
		&i.FailureCode,
		&i.ResultBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
