// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wager_transactions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertWagerTransaction = `-- name: InsertWagerTransaction :exec
INSERT INTO wager_transactions (
    id,
    kind,
    state,
    wallet_id,
    player_id,
    currency,
    amount_minor,
    provider_id,
    external_transaction_id,
    idempotency_key,
    payload_hash,
    round_id,
    game_id,
    reference_external_transaction_id,
    reference_transaction_id,
    failure_code,
    result_balance_minor
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
`

type InsertWagerTransactionParams struct {
	ID                             uuid.UUID
	Kind                           string
	State                          string
	WalletID                       uuid.UUID
	PlayerID                       uuid.UUID
	Currency                       string
	AmountMinor                    int64
	ProviderID                     *string
	ExternalTransactionID          *string
	IdempotencyKey                 *string
	PayloadHash                    *string
	RoundID                        *string
	GameID                         *string
	ReferenceExternalTransactionID *string
	ReferenceTransactionID         *uuid.UUID
	FailureCode                    *string
	ResultBalanceMinor             *int64
}

func (q *Queries) InsertWagerTransaction(ctx context.Context, arg InsertWagerTransactionParams) error {
	_, err := q.db.Exec(ctx, insertWagerTransaction,
		arg.ID,
		arg.Kind,
		arg.State,
		arg.WalletID,
		arg.PlayerID,
		arg.Currency,
		arg.AmountMinor,
		arg.ProviderID,
		arg.ExternalTransactionID,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.RoundID,
		arg.GameID,
		arg.ReferenceExternalTransactionID,
		arg.ReferenceTransactionID,
		arg.FailureCode,
		arg.ResultBalanceMinor,
	)
	return err
}
