// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wager_transactions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const existsProcessedReversal = `-- name: ExistsProcessedReversal :one
SELECT EXISTS (
    SELECT 1
    FROM wager_transactions
    WHERE reference_transaction_id = $1
      AND kind IN ('REFUND', 'ROLLBACK')
      AND state = 'PROCESSED'
)
`

func (q *Queries) ExistsProcessedReversal(ctx context.Context, referenceTransactionID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsProcessedReversal, referenceTransactionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertWagerTransaction = `-- name: InsertWagerTransaction :exec
INSERT INTO wager_transactions (
    id,
    kind,
    state,
    wallet_id,
    player_id,
    currency,
    amount_minor,
    provider_id,
    external_transaction_id,
    idempotency_key,
    payload_hash,
    round_id,
    game_id,
    reference_external_transaction_id,
    reference_transaction_id,
    failure_code,
    result_balance_minor,
    created_at,
    updated_at,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    CASE WHEN $3::text = 'PENDING_REFERENCE' THEN now() END
)
`

type InsertWagerTransactionParams struct {
	ID                             uuid.UUID
	Kind                           string
	State                          string
	WalletID                       uuid.UUID
	PlayerID                       uuid.UUID
	Currency                       string
	AmountMinor                    int64
	ProviderID                     *string
	ExternalTransactionID          *string
	IdempotencyKey                 *string
	PayloadHash                    *string
	RoundID                        *string
	GameID                         *string
	ReferenceExternalTransactionID *string
	ReferenceTransactionID         *uuid.UUID
	FailureCode                    *string
	ResultBalanceMinor             *int64
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

func (q *Queries) InsertWagerTransaction(ctx context.Context, arg InsertWagerTransactionParams) error {
	_, err := q.db.Exec(ctx, insertWagerTransaction,
		arg.ID,
		arg.Kind,
		arg.State,
		arg.WalletID,
		arg.PlayerID,
		arg.Currency,
		arg.AmountMinor,
		arg.ProviderID,
		arg.ExternalTransactionID,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.RoundID,
		arg.GameID,
		arg.ReferenceExternalTransactionID,
		arg.ReferenceTransactionID,
		arg.FailureCode,
		arg.ResultBalanceMinor,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const leasePendingReferences = `-- name: LeasePendingReferences :many
UPDATE wager_transactions
SET next_attempt_at = $1::timestamptz
WHERE id IN (
    SELECT due.id
    FROM wager_transactions AS due
    WHERE due.state = 'PENDING_REFERENCE'
      AND due.next_attempt_at <= $2::timestamptz
    ORDER BY due.next_attempt_at
    LIMIT $3::int
    FOR UPDATE SKIP LOCKED
)
RETURNING id, wallet_id
`

type LeasePendingReferencesParams struct {
	LeaseUntil time.Time
	DueAt      time.Time
	BatchSize  int32
}

type LeasePendingReferencesRow struct {
	ID       uuid.UUID
	WalletID uuid.UUID
}

func (q *Queries) LeasePendingReferences(ctx context.Context, arg LeasePendingReferencesParams) ([]LeasePendingReferencesRow, error) {
	rows, err := q.db.Query(ctx, leasePendingReferences, arg.LeaseUntil, arg.DueAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeasePendingReferencesRow
	for rows.Next() {
		var i LeasePendingReferencesRow
		if err := rows.Scan(&i.ID, &i.WalletID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectWagerTransactionByExternalID = `-- name: SelectWagerTransactionByExternalID :one
SELECT id, kind, state, wallet_id, player_id, currency, amount_minor, provider_id, external_transaction_id, idempotency_key, payload_hash, round_id, game_id, reference_external_transaction_id, reference_transaction_id, failure_code, result_balance_minor, created_at, updated_at, reference_attempts, next_attempt_at
FROM wager_transactions
WHERE provider_id = $1
  AND external_transaction_id = $2
`

type SelectWagerTransactionByExternalIDParams struct {
	ProviderID            *string
	ExternalTransactionID *string
}

func (q *Queries) SelectWagerTransactionByExternalID(ctx context.Context, arg SelectWagerTransactionByExternalIDParams) (WagerTransaction, error) {
	row := q.db.QueryRow(ctx, selectWagerTransactionByExternalID, arg.ProviderID, arg.ExternalTransactionID)
	var i WagerTransaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.WalletID,
		&i.PlayerID,
		&i.Currency,
		&i.AmountMinor,
		&i.ProviderID,
		&i.ExternalTransactionID,
		&i.IdempotencyKey,
		&i.PayloadHash,
		&i.RoundID,
		&i.GameID,
		&i.ReferenceExternalTransactionID,
		&i.ReferenceTransactionID,
		&i.FailureCode,
		&i.ResultBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferenceAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const selectWagerTransactionByID = `-- name: SelectWagerTransactionByID :one
SELECT id, kind, state, wallet_id, player_id, currency, amount_minor, provider_id, external_transaction_id, idempotency_key, payload_hash, round_id, game_id, reference_external_transaction_id, reference_transaction_id, failure_code, result_balance_minor, created_at, updated_at, reference_attempts, next_attempt_at
FROM wager_transactions
WHERE id = $1
`

func (q *Queries) SelectWagerTransactionByID(ctx context.Context, id uuid.UUID) (WagerTransaction, error) {
	row := q.db.QueryRow(ctx, selectWagerTransactionByID, id)
	var i WagerTransaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.WalletID,
		&i.PlayerID,
		&i.Currency,
		&i.AmountMinor,
		&i.ProviderID,
		&i.ExternalTransactionID,
		&i.IdempotencyKey,
		&i.PayloadHash,
		&i.RoundID,
		&i.GameID,
		&i.ReferenceExternalTransactionID,
		&i.ReferenceTransactionID,
		&i.FailureCode,
		&i.ResultBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferenceAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const selectWagerTransactionByIdempotencyKey = `-- name: SelectWagerTransactionByIdempotencyKey :one
SELECT id, kind, state, wallet_id, player_id, currency, amount_minor, provider_id, external_transaction_id, idempotency_key, payload_hash, round_id, game_id, reference_external_transaction_id, reference_transaction_id, failure_code, result_balance_minor, created_at, updated_at, reference_attempts, next_attempt_at
FROM wager_transactions
WHERE provider_id = $1
  AND idempotency_key = $2
`

type SelectWagerTransactionByIdempotencyKeyParams struct {
	ProviderID     *string
	IdempotencyKey *string
}

func (q *Queries) SelectWagerTransactionByIdempotencyKey(ctx context.Context, arg SelectWagerTransactionByIdempotencyKeyParams) (WagerTransaction, error) {
	row := q.db.QueryRow(ctx, selectWagerTransactionByIdempotencyKey, arg.ProviderID, arg.IdempotencyKey)
	var i WagerTransaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.WalletID,
		&i.PlayerID,
		&i.Currency,
		&i.AmountMinor,
		&i.ProviderID,
		&i.ExternalTransactionID,
		&i.IdempotencyKey,
		&i.PayloadHash,
		&i.RoundID,
		&i.GameID,
		&i.ReferenceExternalTransactionID,
		&i.ReferenceTransactionID,
		&i.FailureCode,
		&i.ResultBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferenceAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const updatePendingReference = `-- name: UpdatePendingReference :execrows
UPDATE wager_transactions
SET state = $1,
    failure_code = $2,
    reference_transaction_id = $3,
    result_balance_minor = $4,
    reference_attempts = $5,
    next_attempt_at = $6,
    updated_at = $7
WHERE id = $8
  AND state = 'PENDING_REFERENCE'
`

type UpdatePendingReferenceParams struct {
	State                  string
	FailureCode            *string
	ReferenceTransactionID *uuid.UUID
	ResultBalanceMinor     *int64
	ReferenceAttempts      int32
	NextAttemptAt          *time.Time
	UpdatedAt              time.Time
	ID                     uuid.UUID
}

func (q *Queries) UpdatePendingReference(ctx context.Context, arg UpdatePendingReferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePendingReference,
		arg.State,
		arg.FailureCode,
		arg.ReferenceTransactionID,
		arg.ResultBalanceMinor,
		arg.ReferenceAttempts,
		arg.NextAttemptAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
