// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO wallets (id, player_id, currency, balance_minor, version)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWalletParams struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.ID,
		arg.PlayerID,
		arg.Currency,
		arg.BalanceMinor,
		arg.Version,
	)
	return err
}

const selectWallet = `-- name: SelectWallet :one
SELECT id, player_id, currency, balance_minor, version
FROM wallets
WHERE id = $1
`

type SelectWalletRow struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
}

func (q *Queries) SelectWallet(ctx context.Context, id uuid.UUID) (SelectWalletRow, error) {
	row := q.db.QueryRow(ctx, selectWallet, id)
	var i SelectWalletRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
	)
	return i, err
}

const selectWalletForUpdate = `-- name: SelectWalletForUpdate :one
SELECT id, player_id, currency, balance_minor, version
FROM wallets
WHERE id = $1
FOR UPDATE
`

type SelectWalletForUpdateRow struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
}

func (q *Queries) SelectWalletForUpdate(ctx context.Context, id uuid.UUID) (SelectWalletForUpdateRow, error) {
	row := q.db.QueryRow(ctx, selectWalletForUpdate, id)
	var i SelectWalletForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
	)
	return i, err
}

const selectWalletReconciliation = `-- name: SelectWalletReconciliation :one
SELECT w.currency,
    w.balance_minor,
    COALESCE(SUM(CASE l.direction WHEN 'CREDIT' THEN l.amount_minor ELSE -l.amount_minor END), 0)::bigint
        AS rebuilt_minor,
    count(l.id)::bigint AS checked_entries
FROM wallets AS w
LEFT JOIN wallet_ledger_entries AS l ON l.wallet_id = w.id
WHERE w.id = $1
GROUP BY w.currency, w.balance_minor
`

type SelectWalletReconciliationRow struct {
	Currency       string
	BalanceMinor   int64
	RebuiltMinor   int64
	CheckedEntries int64
}

func (q *Queries) SelectWalletReconciliation(ctx context.Context, id uuid.UUID) (SelectWalletReconciliationRow, error) {
	row := q.db.QueryRow(ctx, selectWalletReconciliation, id)
	var i SelectWalletReconciliationRow
	err := row.Scan(
		&i.Currency,
		&i.BalanceMinor,
		&i.RebuiltMinor,
		&i.CheckedEntries,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :execrows
UPDATE wallets
SET balance_minor = $1,
    version = $2,
    updated_at = now()
WHERE id = $3
  AND version = $4
`

type UpdateWalletBalanceParams struct {
	BalanceMinor    int64
	Version         int64
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWalletBalance,
		arg.BalanceMinor,
		arg.Version,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
