// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_ledger_entries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO wallet_ledger_entries (
    id,
    wallet_id,
    transaction_id,
    direction,
    currency,
    amount_minor,
    balance_before_minor,
    balance_after_minor
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertLedgerEntryParams struct {
	ID                 uuid.UUID
	WalletID           uuid.UUID
	TransactionID      uuid.UUID
	Direction          string
	Currency           string
	AmountMinor        int64
	BalanceBeforeMinor int64
	BalanceAfterMinor  int64
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.WalletID,
		arg.TransactionID,
		arg.Direction,
		arg.Currency,
		arg.AmountMinor,
		arg.BalanceBeforeMinor,
		arg.BalanceAfterMinor,
	)
	return err
}
