// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO wallets (id, player_id, currency, balance_minor, version)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWalletParams struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.ID,
		arg.PlayerID,
		arg.Currency,
		arg.BalanceMinor,
		arg.Version,
	)
	return err
}
