// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO wallets (id, player_id, currency, balance_minor, version)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWalletParams struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.ID,
		arg.PlayerID,
		arg.Currency,
		arg.BalanceMinor,
		arg.Version,
	)
	return err
}

const selectWalletForUpdate = `-- name: SelectWalletForUpdate :one
SELECT id, player_id, currency, balance_minor, version
FROM wallets
WHERE id = $1
FOR UPDATE
`

type SelectWalletForUpdateRow struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
}

func (q *Queries) SelectWalletForUpdate(ctx context.Context, id uuid.UUID) (SelectWalletForUpdateRow, error) {
	row := q.db.QueryRow(ctx, selectWalletForUpdate, id)
	var i SelectWalletForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :execrows
UPDATE wallets
SET balance_minor = $1,
    version = $2,
    updated_at = now()
WHERE id = $3
  AND version = $4
`

type UpdateWalletBalanceParams struct {
	BalanceMinor    int64
	Version         int64
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWalletBalance,
		arg.BalanceMinor,
		arg.Version,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
