// Package postgres implements the use case ports on PostgreSQL, using queries
// generated by sqlc.
package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/davibanfi/betledger/internal/infrastructure/postgres/sqlcgen"
	"github.com/davibanfi/betledger/internal/usecase"
)

var errOutsideTransaction = errors.New("postgres: write attempted outside a transaction")

type txKey struct{}

var _ usecase.Transactor = (*Transactor)(nil)

// Transactor runs units of work inside a PostgreSQL transaction carried by the
// context.
type Transactor struct {
	pool *pgxpool.Pool
}

// NewTransactor builds a Transactor backed by the pool.
func NewTransactor(pool *pgxpool.Pool) *Transactor {
	return &Transactor{pool: pool}
}

// WithinTransaction begins a transaction, runs fn with it in the context, and
// commits when fn succeeds. Any error from fn rolls the transaction back.
func (t *Transactor) WithinTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	tx, err := t.pool.Begin(ctx)
	if err != nil {
		return translate(fmt.Errorf("begin transaction: %w", err))
	}
	defer func() { _ = tx.Rollback(context.WithoutCancel(ctx)) }()

	if err := fn(context.WithValue(ctx, txKey{}, tx)); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return translate(fmt.Errorf("commit transaction: %w", err))
	}
	return nil
}

func queries(ctx context.Context) (*sqlcgen.Queries, error) {
	tx, ok := ctx.Value(txKey{}).(pgx.Tx)
	if !ok {
		return nil, errOutsideTransaction
	}
	return sqlcgen.New(tx), nil
}
